# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XSjenu76ES5q_jbUbRjUsbFoTatxXkIX

# Install Three Library 
**Using  pip3 we install these three library**

**Import Three Dependent Library**
"""

import requests
import pandas as pd
import pdfplumber

pdf = "/content/drive/MyDrive/Colab Notebooks/table.pdf" ## My Local SamplePdfFile

with pdfplumber.open(pdf) as df:
  page = df.pages[0]   ## For Page Number 
  text = page.extract_text()  ## To Extract The Text

print(text)  ## Now Our Pdf Tabluar Data Extract into Text